"""add worker home_site_id

Revision ID: 1698aaafb524
Revises: 58bbbc034a0f
Create Date: 2026-09-22 07:43:22.103040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1698aaafb524'
down_revision: Union[str, Sequence[str], None] = '58bbbc034a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('home_site_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_worker_home_site_id'), 'worker', ['home_site_id'], unique=False)
    op.create_foreign_key(op.f('fk_worker_home_site_id_site'), 'worker', 'site', ['home_site_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_worker_home_site_id_site'), 'worker', type_='foreignkey')
    op.drop_index(op.f('ix_worker_home_site_id'), table_name='worker')
    op.drop_column('worker', 'home_site_id')
    # ### end Alembic commands ###
