"""add worker employee_code and award_cost_matrix is_placeholder

Revision ID: 444a18bc4940
Revises: d654884bf05e
Create Date: 2026-09-23 20:54:04.499649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444a18bc4940'
down_revision: Union[str, Sequence[str], None] = 'd654884bf05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('award_cost_matrix', sa.Column('is_placeholder', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('worker', sa.Column('employee_code', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_worker_employee_code'), 'worker', ['employee_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_employee_code'), table_name='worker')
    op.drop_column('worker', 'employee_code')
    op.drop_column('award_cost_matrix', 'is_placeholder')
    # ### end Alembic commands ###
