"""Add ORL domain models

Revision ID: 58bbbc034a0f
Revises: 
Create Date: 2026-09-22 07:00:44.887109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58bbbc034a0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SOLVED', 'FAILED', name='roster_status'), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roster'))
    )
    op.create_index('ix_roster_period', 'roster', ['period_start', 'period_end'], unique=False)
    op.create_index(op.f('ix_roster_status'), 'roster', ['status'], unique=False)
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site'))
    )
    op.create_index(op.f('ix_site_code'), 'site', ['code'], unique=True)
    op.create_index(op.f('ix_site_region'), 'site', ['region'], unique=False)
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker'))
    )
    op.create_index(op.f('ix_worker_active'), 'worker', ['active'], unique=False)
    op.create_index(op.f('ix_worker_region'), 'worker', ['region'], unique=False)
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('required_skill', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('is_multi_stop', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_shift_site_id_site')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift'))
    )
    op.create_index(op.f('ix_shift_date'), 'shift', ['date'], unique=False)
    op.create_index('ix_shift_date_required_skill', 'shift', ['date', 'required_skill'], unique=False)
    op.create_index(op.f('ix_shift_is_multi_stop'), 'shift', ['is_multi_stop'], unique=False)
    op.create_index(op.f('ix_shift_required_skill'), 'shift', ['required_skill'], unique=False)
    op.create_index(op.f('ix_shift_site_id'), 'shift', ['site_id'], unique=False)
    op.create_table('award_cost_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('pay_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('min_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], name=op.f('fk_award_cost_matrix_shift_id_shift')),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], name=op.f('fk_award_cost_matrix_worker_id_worker')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_award_cost_matrix')),
    sa.UniqueConstraint('worker_id', 'day', 'shift_id', name='uq_award_cost_matrix_key')
    )
    op.create_index(op.f('ix_award_cost_matrix_day'), 'award_cost_matrix', ['day'], unique=False)
    op.create_index(op.f('ix_award_cost_matrix_shift_id'), 'award_cost_matrix', ['shift_id'], unique=False)
    op.create_index(op.f('ix_award_cost_matrix_worker_id'), 'award_cost_matrix', ['worker_id'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('sequence_hint', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], name=op.f('fk_job_shift_id_shift')),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_job_site_id_site')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    op.create_index(op.f('ix_job_shift_id'), 'job', ['shift_id'], unique=False)
    op.create_index('ix_job_shift_site', 'job', ['shift_id', 'site_id'], unique=False)
    op.create_index(op.f('ix_job_site_id'), 'job', ['site_id'], unique=False)
    op.create_table('roster_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roster_id'], ['roster.id'], name=op.f('fk_roster_assignment_roster_id_roster')),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], name=op.f('fk_roster_assignment_shift_id_shift')),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], name=op.f('fk_roster_assignment_worker_id_worker')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roster_assignment')),
    sa.UniqueConstraint('roster_id', 'worker_id', 'day', 'shift_id', name='uq_roster_assignment_key')
    )
    op.create_index(op.f('ix_roster_assignment_day'), 'roster_assignment', ['day'], unique=False)
    op.create_index(op.f('ix_roster_assignment_roster_id'), 'roster_assignment', ['roster_id'], unique=False)
    op.create_index(op.f('ix_roster_assignment_shift_id'), 'roster_assignment', ['shift_id'], unique=False)
    op.create_index('ix_roster_assignment_worker_day_shift', 'roster_assignment', ['worker_id', 'day', 'shift_id'], unique=False)
    op.create_index(op.f('ix_roster_assignment_worker_id'), 'roster_assignment', ['worker_id'], unique=False)
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roster_assignment_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SOLVED', 'FAILED', 'SUPERSEDED', name='route_status'), nullable=False),
    sa.ForeignKeyConstraint(['roster_assignment_id'], ['roster_assignment.id'], name=op.f('fk_route_roster_assignment_id_roster_assignment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route'))
    )
    op.create_index(op.f('ix_route_roster_assignment_id'), 'route', ['roster_assignment_id'], unique=True)
    op.create_index(op.f('ix_route_status'), 'route', ['status'], unique=False)
    op.create_table('site_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roster_assignment_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('departure', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['roster_assignment_id'], ['roster_assignment.id'], name=op.f('fk_site_assignment_roster_assignment_id_roster_assignment')),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_site_assignment_site_id_site')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_assignment'))
    )
    op.create_index(op.f('ix_site_assignment_roster_assignment_id'), 'site_assignment', ['roster_assignment_id'], unique=True)
    op.create_index(op.f('ix_site_assignment_site_id'), 'site_assignment', ['site_id'], unique=False)
    op.create_table('reoptimization_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('JOB_CANCELLED', 'WORKER_SICK', 'VISIT_OVERRAN', name='reoptimization_event_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.Enum('SCOPED_RESOLVE', 'ESCALATED_TO_TIER1', name='reoptimization_resolution'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVING', 'RESOLVED', 'ESCALATED', name='reoptimization_status'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name=op.f('fk_reoptimization_event_route_id_route')),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], name=op.f('fk_reoptimization_event_shift_id_shift')),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], name=op.f('fk_reoptimization_event_worker_id_worker')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reoptimization_event'))
    )
    op.create_index('ix_reopt_event_occurred_at', 'reoptimization_event', ['occurred_at'], unique=False)
    op.create_index('ix_reopt_event_route_shift_worker', 'reoptimization_event', ['route_id', 'shift_id', 'worker_id'], unique=False)
    op.create_index(op.f('ix_reoptimization_event_event_type'), 'reoptimization_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_reoptimization_event_route_id'), 'reoptimization_event', ['route_id'], unique=False)
    op.create_index(op.f('ix_reoptimization_event_shift_id'), 'reoptimization_event', ['shift_id'], unique=False)
    op.create_index(op.f('ix_reoptimization_event_status'), 'reoptimization_event', ['status'], unique=False)
    op.create_index(op.f('ix_reoptimization_event_worker_id'), 'reoptimization_event', ['worker_id'], unique=False)
    op.create_table('route_stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('planned_arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_departure', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_route_stop_job_id_job')),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name=op.f('fk_route_stop_route_id_route')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_stop')),
    sa.UniqueConstraint('route_id', 'job_id', name='uq_route_stop_job'),
    sa.UniqueConstraint('route_id', 'sequence_no', name='uq_route_stop_sequence')
    )
    op.create_index(op.f('ix_route_stop_job_id'), 'route_stop', ['job_id'], unique=False)
    op.create_index(op.f('ix_route_stop_route_id'), 'route_stop', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_stop_route_id'), table_name='route_stop')
    op.drop_index(op.f('ix_route_stop_job_id'), table_name='route_stop')
    op.drop_table('route_stop')
    op.drop_index(op.f('ix_reoptimization_event_worker_id'), table_name='reoptimization_event')
    op.drop_index(op.f('ix_reoptimization_event_status'), table_name='reoptimization_event')
    op.drop_index(op.f('ix_reoptimization_event_shift_id'), table_name='reoptimization_event')
    op.drop_index(op.f('ix_reoptimization_event_route_id'), table_name='reoptimization_event')
    op.drop_index(op.f('ix_reoptimization_event_event_type'), table_name='reoptimization_event')
    op.drop_index('ix_reopt_event_route_shift_worker', table_name='reoptimization_event')
    op.drop_index('ix_reopt_event_occurred_at', table_name='reoptimization_event')
    op.drop_table('reoptimization_event')
    op.drop_index(op.f('ix_site_assignment_site_id'), table_name='site_assignment')
    op.drop_index(op.f('ix_site_assignment_roster_assignment_id'), table_name='site_assignment')
    op.drop_table('site_assignment')
    op.drop_index(op.f('ix_route_status'), table_name='route')
    op.drop_index(op.f('ix_route_roster_assignment_id'), table_name='route')
    op.drop_table('route')
    op.drop_index(op.f('ix_roster_assignment_worker_id'), table_name='roster_assignment')
    op.drop_index('ix_roster_assignment_worker_day_shift', table_name='roster_assignment')
    op.drop_index(op.f('ix_roster_assignment_shift_id'), table_name='roster_assignment')
    op.drop_index(op.f('ix_roster_assignment_roster_id'), table_name='roster_assignment')
    op.drop_index(op.f('ix_roster_assignment_day'), table_name='roster_assignment')
    op.drop_table('roster_assignment')
    op.drop_index(op.f('ix_job_site_id'), table_name='job')
    op.drop_index('ix_job_shift_site', table_name='job')
    op.drop_index(op.f('ix_job_shift_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_award_cost_matrix_worker_id'), table_name='award_cost_matrix')
    op.drop_index(op.f('ix_award_cost_matrix_shift_id'), table_name='award_cost_matrix')
    op.drop_index(op.f('ix_award_cost_matrix_day'), table_name='award_cost_matrix')
    op.drop_table('award_cost_matrix')
    op.drop_index(op.f('ix_shift_site_id'), table_name='shift')
    op.drop_index(op.f('ix_shift_required_skill'), table_name='shift')
    op.drop_index(op.f('ix_shift_is_multi_stop'), table_name='shift')
    op.drop_index('ix_shift_date_required_skill', table_name='shift')
    op.drop_index(op.f('ix_shift_date'), table_name='shift')
    op.drop_table('shift')
    op.drop_index(op.f('ix_worker_region'), table_name='worker')
    op.drop_index(op.f('ix_worker_active'), table_name='worker')
    op.drop_table('worker')
    op.drop_index(op.f('ix_site_region'), table_name='site')
    op.drop_index(op.f('ix_site_code'), table_name='site')
    op.drop_table('site')
    op.drop_index(op.f('ix_roster_status'), table_name='roster')
    op.drop_index('ix_roster_period', table_name='roster')
    op.drop_table('roster')
    # ### end Alembic commands ###

    # NOTE: hand-added, not autogenerated. Alembic's `op.drop_table()` only
    # drops the table -- it does NOT emit `DROP TYPE` for the native
    # Postgres enums (created via `sa.Enum(..., name=...)`) that table's
    # columns used, even though `op.create_table()` in `upgrade()` above
    # *did* emit `CREATE TYPE` for them as a side effect of creating the
    # column. Left unfixed, `downgrade()` leaves these enum types behind in
    # the database, and a subsequent `upgrade()` then fails with
    # "type ... already exists" (verified by actually running
    # `upgrade -> downgrade -> upgrade` against a live Postgres instance).
    # We drop them explicitly here, in reverse dependency order, after all
    # tables that reference them are gone.
    sa.Enum(name='reoptimization_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='reoptimization_resolution').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='reoptimization_event_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='route_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='roster_status').drop(op.get_bind(), checkfirst=True)
