"""add worker award fields and roster engine cost reconciliation

Revision ID: 7c3e9a1d5b20
Revises: 444a18bc4940
Create Date: 2026-09-25 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7c3e9a1d5b20'
down_revision: Union[str, Sequence[str], None] = '444a18bc4940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Hand-written (not autogenerated). Native Postgres enums, labelled with the
# Python enum member *names* -- the same convention SQLAlchemy's
# `Enum(SomeStrEnum, name=...)` uses for every existing enum in this schema
# (see 58bbbc034a0f). `create_type=False` + an explicit `.create()` because
# `op.add_column()`, unlike `op.create_table()`, does not emit CREATE TYPE.
employment_type = postgresql.ENUM(
    'FULL_TIME', 'PART_TIME', 'CASUAL', name='employment_type', create_type=False
)
roster_cost_status = postgresql.ENUM(
    'ENGINE_EXACT',
    'ENGINE_UNRESOLVED',
    'ENGINE_UNAVAILABLE',
    'ENGINE_REJECTED',
    'PLACEHOLDER_ESTIMATE',
    name='roster_cost_status',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    employment_type.create(bind, checkfirst=True)
    roster_cost_status.create(bind, checkfirst=True)

    op.add_column('worker', sa.Column('award_code', sa.String(length=16), nullable=True))
    op.add_column('worker', sa.Column('classification_level', sa.String(length=64), nullable=True))
    op.add_column('worker', sa.Column('employment_type', employment_type, nullable=True))
    op.add_column('worker', sa.Column('over_award_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('worker', sa.Column('ordinary_hours_per_week', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('worker', sa.Column('agreed_ordinary_hours_per_shift', sa.Numeric(precision=5, scale=2), nullable=True))

    op.add_column('roster', sa.Column('engine_total_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('roster', sa.Column('engine_commit', sa.String(length=64), nullable=True))
    op.add_column('roster', sa.Column('cost_status', roster_cost_status, nullable=True))
    op.add_column('roster', sa.Column('cost_detail', sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('roster', 'cost_detail')
    op.drop_column('roster', 'cost_status')
    op.drop_column('roster', 'engine_commit')
    op.drop_column('roster', 'engine_total_cost')

    op.drop_column('worker', 'agreed_ordinary_hours_per_shift')
    op.drop_column('worker', 'ordinary_hours_per_week')
    op.drop_column('worker', 'over_award_rate')
    op.drop_column('worker', 'employment_type')
    op.drop_column('worker', 'classification_level')
    op.drop_column('worker', 'award_code')

    bind = op.get_bind()
    roster_cost_status.drop(bind, checkfirst=True)
    employment_type.drop(bind, checkfirst=True)
