"""add travel matrix entry and roster failure_reason

Revision ID: d654884bf05e
Revises: 1698aaafb524
Create Date: 2026-09-22 08:11:53.885573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd654884bf05e'
down_revision: Union[str, Sequence[str], None] = '1698aaafb524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_matrix_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_site_id', sa.Integer(), nullable=False),
    sa.Column('to_site_id', sa.Integer(), nullable=False),
    sa.Column('travel_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_site_id'], ['site.id'], name=op.f('fk_travel_matrix_entry_from_site_id_site')),
    sa.ForeignKeyConstraint(['to_site_id'], ['site.id'], name=op.f('fk_travel_matrix_entry_to_site_id_site')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_travel_matrix_entry')),
    sa.UniqueConstraint('from_site_id', 'to_site_id', name='uq_travel_matrix_entry_site_pair')
    )
    op.create_index(op.f('ix_travel_matrix_entry_from_site_id'), 'travel_matrix_entry', ['from_site_id'], unique=False)
    op.create_index(op.f('ix_travel_matrix_entry_to_site_id'), 'travel_matrix_entry', ['to_site_id'], unique=False)
    op.add_column('roster', sa.Column('failure_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roster', 'failure_reason')
    op.drop_index(op.f('ix_travel_matrix_entry_to_site_id'), table_name='travel_matrix_entry')
    op.drop_index(op.f('ix_travel_matrix_entry_from_site_id'), table_name='travel_matrix_entry')
    op.drop_table('travel_matrix_entry')
    # ### end Alembic commands ###
